AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiProxy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/apiproxy.handler
      CodeUri: dist/app
      Runtime: nodejs12.x
      MemorySize: 256
      Timeout: 10
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/lambda.handler
      CodeUri: dist/app
      Runtime: nodejs12.x
      MemorySize: 256
      Timeout: 10
